# Generated by Django 3.1.7 on 2021-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('rec_id', models.CharField(max_length=800, primary_key=True, serialize=False, unique=True)),
                ('photo', models.URLField(max_length=1000)),
                ('FIO', models.CharField(max_length=800)),
                ('methods', models.JSONField()),
            ],
        ),
    ]
