# Generated by Django 3.1.7 on 2021-02-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='rec_id',
            field=models.CharField(max_length=800, primary_key=True, serialize=False),
        ),
    ]
