# Generated by Django 3.1.7 on 2021-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0003_auto_20210222_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='FIO',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='photo',
            field=models.TextField(),
        ),
    ]
