# Generated by Django 3.1.7 on 2021-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_auto_20210222_0154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='therapist',
            table='therapist',
        ),
    ]
